kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: brewctl-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Mude a porta 80 para 8080
  - containerPort: 80
    hostPort: 8080 # ✅ ALTERADO: 80 → 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 8443 # ✅ ALTERADO: 443 → 8443  
    protocol: TCP
  - containerPort: 8000
    hostPort: 8000
    protocol: TCP
  - containerPort: 3000
    hostPort: 3000
    protocol: TCP
  - containerPort: 9090
    hostPort: 9090
    protocol: TCP
  - containerPort: 27017
    hostPort: 27017
    protocol: TCP
